In [ ]:
!pip install html-table-parser-python3

Collecting html-table-parser-python3
  Downloading html_table_parser_python3-0.3.1-py3-none-any.whl (15 kB)
Installing collected packages: html-table-parser-python3
Successfully installed html-table-parser-python3-0.3.1

In [10]:
# Library for opening url and creating requests
import urllib.request

# pretty-print python data structures
from pprint import pprint

# for parsing all the tables present on the website
from html_table_parser.parser import HTMLTableParser

# for converting the parsed data in a pandas dataframe
import pandas as pd

In [11]:
# Opens a website and read its binary contents (HTTP Response Body)
def url_get_contents(url):

    # making request to the website
    req = urllib.request.Request(url=url)
    f = urllib.request.urlopen(req)

    # reading contents of the website
    return f.read()

In [22]:
#@title Insert Link Here { run: "auto" }
# defining the html contents of a URL.
link_url = "https://www.vlr.gg/stats/?event_group_id=45&event_id=1494&series_id=all&region=all&country=all&min_rounds=200&min_rating=1550&agent=all&map_id=all&timespan=60d" #@param {type:"string"}
xhtml = url_get_contents(link_url).decode('utf-8')

# Defining the HTMLTableParser object
p = HTMLTableParser()

# feeding the html contents in the HTMLTableParser object
p.feed(xhtml)

In [24]:
df = pd.DataFrame(p.tables[0])
df.columns = df.iloc[0]
df = df[1:]
df.head()

,Player,Agents,Rnd,R,ACS,K:D,KAST,ADR,KPR,APR,...,FDPR,HS%,CL%,CL,KMax,K,D,A,FK,FD
1,Alfajer FNC,,210,1.31,229.2,1.63,80%,143.3,0.88,0.16,...,0.06,29%,21%,6/29,25,184,113,34,23,12
2,Leo FNC,,210,1.29,200.9,1.47,80%,129.4,0.71,0.45,...,0.01,18%,18%,4/22,26,150,102,94,11,2
3,Chronicle FNC,,210,1.21,236.8,1.33,76%,149.6,0.83,0.43,...,0.09,26%,,0/11,22,174,131,91,15,19
4,ZmjjKK EDG,,341,1.15,273.8,1.30,73%,169.7,0.96,0.17,...,0.16,19%,13%,3/23,30,329,254,59,82,54
5,Derke FNC,,210,1.12,247.3,1.18,70%,157.7,0.82,0.20,...,0.22,22%,38%,3/8,28,173,147,42,51,47